site_name: 'Cloud Native DevSecOps'

nav:
- Project: 'index.md'
- Contents: 'contents.md'
- Introduction: 'introduction.md' 
- Problem Statement: 'problem-statement.md'
- SAST Github Action: 'github-action.md'
- Code Quality Analysis: 'code-quality-analysis.md'
- Software Bill of Materials: 'sbom.md'
- Setting Up Application through AWS: 'setting-app-aws.md'
- Setting Up GitHub Actions Workflow for DAST: 'dast.md'
- Setting Up GitHub Actions Workflow for Deployment: 'deployment.md'
- Conclusion: 'Conclusion.md'
- Resources: 'resources.md'

theme: material