site_name: 'DevSecOps'

pages:
- Introduction: 'index.md'
- Setup of VMs: 'Ubuntu-server-VM-setup.md'
- Setup of Jenkins: 'Jenkins-installation.md'
- MkDocs | setup, usage: 'mkdocs-setup-usage.md'

theme: material
