site_name: 'DevSecOps Pipeline'

nav:
- Introduction: 'index.md'
- Contents: 'contents.md'
- Problem Statement: 'problem-statement.md'
- Setting Up VM: 'Ubuntu-server-VM-setup.md'
- Setting Up Jenkins: 'Jenkins-installation.md'
- Setting Up MkDocs for report: 'mkdocs-setup-usage.md'
- Setting Up Pipeline: 'setting-up-pipeline.md'
- Setting Up SuiteCRM: 'setting-up-suitecrm.md'
- Deployment of SuiteCRM: 'deployment-of-suitecrm.md'
- Static Analysis of SuiteCRM: 'sast-tools.md'
- Dynamic Analysis of SuiteCRM: 'dast-tools.md'
- Software Bill of Materials: 'sbom.md'
- Source Code Quality Analysis: 'linting-tool.md'
- Performing DAST of SuiteCRM through Docker: 'docker.md'
- Complete Pipeline Structure: 'complete-pipeline-structure.md'

theme: material