site_name: 'DevSecOps Pipeline - cloud'

nav:
- Introduction: 'index.md'
- Contents: 'contents.md'
- Problem Statement: 'problem-statement.md'
- SAST Github Action: 'github-action.md'

theme: material