site_name: 'Cloud Native Implementation of DevSecOps Concepts'

nav:
- Introduction: 'index.md'
- Contents: 'contents.md'
- Problem Statement: 'problem-statement.md'
- SAST Github Action: 'github-action.md'
- Code Quality Analysis: 'code-quality-analysis.md'
- Software Bill of Materials: 'sbom.md'
- Set up GitHub Actions Workflow for DAST: 'dast.md'
- Set up GitHub Actions Workflow for Deployment: 'deployment.md'

theme: material