site_name: 'DevSecOps'

nav:
- Introduction: 'index.md'
- Contents: 'contents.md'
- Problem Statement: 'problem-statement.md'
- Setup of VMs: 'Ubuntu-server-VM-setup.md'
- Setup of Jenkins: 'Jenkins-installation.md'
- MkDocs setup for report: 'mkdocs-setup-usage.md'

theme: material
